## Travis CI Integration
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
      dotnet: 2.1  # Installed by apt-get, it installs the latest 2.1.X
    - os: osx
      osx_image: xcode10
      mono: latest
      dotnet: 2.1.403  # Installed by downloading manually packages.

script:
- ./build.sh --target=Travis --verbosity=diagnostic
